---
title: "Estadística descriptiva con R"
author: 'statsanddatasci'
date: '2019-06-05'
categories: []
tags: ["rstas", "rstatses"]
---



<div id="datos-a-utilizar" class="section level3">
<h3>Datos a utilizar</h3>
<p>Se usa el conjunto de datos (dataset) <code>mtcars</code>:</p>
<pre class="r"><code>head(mtcars)</code></pre>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
</div>
<div id="estadistica-descriptiva-de-la-variable-cyl" class="section level3">
<h3>Estadística descriptiva de la variable <code>cyl</code></h3>
<ol style="list-style-type: decimal">
<li>Tablas de frecuencia</li>
</ol>
<pre class="r"><code>(tablaFrecAbs = table(mtcars$cyl))</code></pre>
<pre><code>## 
##  4  6  8 
## 11  7 14</code></pre>
<p>Estos resultados anteriores se puede interpretar de la siguiente manera:</p>
<p>14 automóviles tiene 8 cilindros, 11 tiene 4 cilindros y 7 automóviles tienen 6 cilindros.</p>
<p>En ocaciones es má cómodo interpretar en porcentajes:</p>
<pre class="r"><code>(tablaFrecAbs = table(mtcars$cyl)/length(mtcars$cyl))*100</code></pre>
<pre><code>## 
##      4      6      8 
## 34.375 21.875 43.750</code></pre>
<p>Por ejmplo:</p>
<p>El 43.75% de automóviles tienen 8 cilindros.</p>
<p>Con las frecuencias podemos realizar un gráfico de barras</p>
<pre class="r"><code>barplot(tablaFrecAbs)</code></pre>
<p><img src="/post/estadistica-descriptiva_files/figure-html/unnamed-chunk-4-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>El mismo gráfico anerior se puede realizar con el paquete <a href="https://ggplot2.tidyverse.org/"><code>ggplo2</code></a> pero en este caso usando la variable del <strong>dataset</strong>:</p>
<pre class="r"><code>library(ggplot2)
ggplot(mtcars, aes(cyl, ..prop..)) +
  geom_bar(fill=&quot;blue&quot;, color=&quot;red&quot;)</code></pre>
<p><img src="/post/estadistica-descriptiva_files/figure-html/unnamed-chunk-5-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>En el gráfico podemos contrastar que existe más automóviles con 8 cilindros.</p>
<p><strong><em>Es muy importante endender y tener claro los tipos de variables, aquí hago refefencia una imagen de <a href="https://conceptosclaros.com/como-analizar-datos/tipos-variables-720x518-5/">conceptosclaros.com</a></em></strong></p>
<center>
<img src="https://conceptosclaros.com/wp-content/uploads/2017/06/tipos-variables-720x518-5.jpg" style="width:50.0%;height:50.0%" />
</center>
</div>
<div id="estadistica-descriptiva-de-la-variable-disp" class="section level3">
<h3>Estadística descriptiva de la variable <code>disp</code></h3>
<p>En este caso el tipo de variable es cuantitativa continua.</p>
<ol style="list-style-type: decimal">
<li>Medidas de tendencia central</li>
</ol>
<p>Entre las medidas de tendencia central tenemos:</p>
<ul>
<li>Media aritmética</li>
<li>Media geométrica</li>
<li>Media armónica</li>
<li>Mediana</li>
<li>Moda</li>
</ul>
<pre class="r"><code>library(dplyr)
library(modeest)
mtcars %&gt;% 
  summarise(mari =  mean(disp),
            mgeo = 1/mean(1/disp),
            marm = prod(disp)^(1/length(disp)),
            mediana = median(disp),
            moda = modeest::mlv(disp)) </code></pre>
<pre><code>##       mari     mgeo     marm mediana     moda
## 1 230.7219 166.7994 197.3218   196.3 122.2938</code></pre>
<p>El desplazamiento promedio de los automóviles es de 230.72 cu.in., El 50% de automóviles tienen un desplazamiento menor o igual a 196.3 cu.in. y el desplazamiento con mayor frecuencia es de 122.30 cu.in.</p>
<ol style="list-style-type: decimal">
<li>Medidas de dispersión</li>
</ol>
<ul>
<li>Desviación típica</li>
<li>Rango</li>
<li>Rango intercuartílico</li>
<li>Varianza</li>
<li>Desviación media absoluta (MAD)</li>
<li>Coeficiente de variación</li>
</ul>
<pre class="r"><code>library(dplyr)
mtcars %&gt;% 
  summarise(Var =  var(disp),
            sd = sd(disp),
            IQR = IQR(disp),
            cv = sd(disp)/abs(mean(disp))) </code></pre>
<pre><code>##       Var       sd     IQR        cv
## 1 15360.8 123.9387 205.175 0.5371779</code></pre>
<p>Los datos están dispersos de la media.</p>
<ol start="3" style="list-style-type: decimal">
<li>Medidas de Forma</li>
</ol>
<pre class="r"><code>library(e1071)
skewness(mtcars[,&quot;mpg&quot;],type = 1)</code></pre>
<pre><code>## [1] 0.6404399</code></pre>
<pre class="r"><code>kurtosis(mtcars[,&quot;mpg&quot;],type = 1)</code></pre>
<pre><code>## [1] -0.2005332</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Gráficos</li>
</ol>
<pre class="r"><code>library(ggplot2)
ggplot(mtcars, aes(disp))+
  geom_histogram(bins=10)</code></pre>
<p><img src="/post/estadistica-descriptiva_files/figure-html/unnamed-chunk-9-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
